### ISSUE TITLE
CPU Turn On And Off Time

### ISSUE THREAD

**Issue by ChetanArvindPatil** [mad-ady/odroid-xu3-cpu-control#2]
Hi,

Is it possible to calculate time it takes to bring core online if it's offline? I turn cores on and off using sysfs.

Thanks.

**Comment by mad-ady** [comment]
I'm not sure how you can calculate it. If I remember correctly, when using
hotplug it would say in dmesg when it was taking a core offline (and when
it was shut down), so you may be able to time it from there.
